Repository hanami/guides, pull requests merged in 2022-11, with the labels that each got.

#114 Add work-in-progress 2.0 guides.
  content/v2.0/_index.md
  content/v2.0/actions/_index.md
  content/v2.0/actions/overview.md
  content/v2.0/architecture/_index.md
  content/v2.0/architecture/containers.md
  content/v2.0/architecture/providers.md
  content/v2.0/architecture/slices.md
  content/v2.0/introduction/_index.md
  content/v2.0/introduction/getting-started.md
  content/v2.0/routing/_index.md
  content/v2.0/routing/overview.md
Labels: documentation, ready for review

#115 Ensure version switcher to land to Getting Started page
  config.toml
  themes/hanami/layouts/_default/single.html
  themes/hanami/layouts/index.html
Labels: fix

#116 Add 2.0 getting started walk through.
  content/v2.0/introduction/getting-started.md
  content/v2.0/introduction/hello-from-hanami.png
Labels: documentation

#121 Guides 2.0 Actions # parameters
  content/v2.0/actions/overview.md
  content/v2.0/actions/parameters.md
Labels: documentation, ready for review

#117 Guides 2.0 - Actions# Request and Response objects
  content/v2.0/actions/overview.md
  content/v2.0/actions/request-and-response.md
Labels: documentation, ready for review

#135 Tweak CSS a bit
  content/v2.0/logger/configuration.md
  content/v2.0/logger/usage.md
  themes/hanami/static/assets/css/theme.css
Labels: enhancement

#118 Guides 2.0 - Actions # Exception Handling
  content/v2.0/actions/default-error-response.png
  content/v2.0/actions/exception-handling.md
  content/v2.0/actions/overview.md
Labels: documentation, ready for review

#131 Add actions-mime-types and format section
  content/v2.0/actions/formats-and-mime-types.md
  content/v2.0/actions/overview.md
Labels: documentation, ready for review

#119 Guides 2.0 - Actions # Control Flow section
  content/v2.0/actions/404-response.png
  content/v2.0/actions/control-flow.md
  content/v2.0/actions/overview.md
Labels: documentation, ready for review

#147 Add actions-testing section
  content/v2.0/actions/overview.md
  content/v2.0/actions/testing.md
Labels: documentation, ready for review

#146 Add actions-http-caching
  content/v2.0/actions/http-caching.md
Labels: documentation, ready for review

#132 Docs/309 actions sessions and cookies
  content/v2.0/actions/cookies.md
  content/v2.0/actions/sessions.md
Labels: documentation, ready for review

#120 Guides 2.0 - Actions # Rack middleware
  content/v2.0/actions/rack-integration.md
Labels: documentation, ready for review
